### ISSUE TITLE
how to use in code

### ISSUE THREAD

**Issue by JslinSir** [listenzz/react-native-modal-translucent#2]
how to use in code

**Comment by JslinSir** [comment]
![image](https://user-images.githubusercontent.com/30678791/40343786-3d53dd1c-5dc4-11e8-8531-1e8c438737c3.png)
When I use this component, it is strange that the status bar appears at the bottom.

**Comment by JslinSir** [comment]
And when I uninstall, RN's original modal doesn't work.

**Comment by listenzz** [comment]
delete node_modules dir, and install again.

the bottom is the view under modal, not the status bar, since the dimming view of modal do not cover the screen completely.

**Comment by JslinSir** [comment]
I hope this component can be more perfect

**Comment by listenzz** [comment]
Have you use the StatusBar Api?  It seems that the toolbar's height is not correct.

May you paste your Modal and it's host component code here?

**Comment by JslinSir** [comment]
yes ,I used StatusBar in other components:
<View>
   {Platform.OS === 'android' && <StatusBar
          barStyle={'dark-content'}
          backgroundColor={this.state.statusBarBackground}
          animated={true}
          translucent={true}
        />}
</View>

but  this components i dont user the StatusBar 

  <View style={{position:"absolute", top:0, bottom:0, left:0, right:0}}>
             <Modal
               animationType={"slide"}
               transparent={true}
               visible={this.props.modalVisible}
               onRequestClose={() => { this._pressSignClose() }}
              >
            <TouchableOpacity style={styles.ModalView} onPress={() => {
                this._Close()
            }}>
                <View style={styles.bottomView}>
                    <TouchableOpacity style={[styles.bottomItems, styles.bottomLine]}
                        onPress={() => {
                            this.Photograph()
                        }}
                    >
                        <Text style={styles.textBottom}>拍照</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={[styles.bottomItems, styles.bottomLine]}
                        onPress={() => {
                            this.Selectalbum()
                        }}
                    >
                        <Text style={styles.textBottom}>从手机相册选择</Text>
                    </TouchableOpacity>
                    <View style={styles.Lineanoth}>
                    </View>
                    <TouchableOpacity style={[styles.bottomItems]} onPress={() => {
                        this._Close()
                    }}>
                        <Text style={styles.textBottom}>取消</Text>
                    </TouchableOpacity>
                </View>

            </TouchableOpacity>
            </Modal>
            </View>

**Comment by JslinSir** [comment]
I tried to annotate all the StatusBar in the code, but I still have the same problem. I really don't know why.
![image](https://user-images.githubusercontent.com/30678791/40362523-51fc4e26-5dff-11e8-80b9-3cf07812e7f1.png)

**Comment by JslinSir** [comment]
it`s amazing when I opened the debug mode:"JS debugging". the blank part of the bottom of  disappeared.

**Comment by servocoder** [comment]
@JslinSir Have you checked how is behaves at a real device?

**Comment by JslinSir** [comment]
@servocoder Yes, the same will happen. Now I switch to RN modal.

**Comment by listenzz** [comment]
@JslinSir In the latest version, this issue has been fixed, maybe you can try again
