### ISSUE TITLE
What does `npm run fix-modal` do?

### ISSUE THREAD

**Issue by alvintheodora** [listenzz/react-native-modal-translucent#20]
Hi, great fix btw, but I'd like to know what does `npm run fix-modal` do?
It doesnt change any files when I ran `git status`. Does it mean when I re-clone my repository, I need to run `npm run fix-modal` again?
Cheers

**Comment by listenzz** [comment]
It modify node_modules/react-native/Libraries/Modal/Modal.js.

If you setup your package.json file as README, don't need to run `npm run fix-modal`

**Comment by alvintheodora** [comment]
Do you have the changelog of what you changed to the Modal.js?

**Comment by listenzz** [comment]
Just use [this script](https://github.com/listenzz/react-native-modal-translucent/blob/master/scripts/translucent-modal.js) to replace the underlying implementation.
