### ISSUE TITLE
Can't find variable: requireNativeComponent

### ISSUE THREAD

**Issue by P21Marcelo** [listenzz/react-native-modal-translucent#21]
I got the following error after i upgraded for RN 0.59.4;
what i already did:
 ---> made a test and the error just happens after i run "npm run fix-modal"
----> error is happening for both, Android and IOS
----> app runs just fine if i dont run the post install and "npm run fix-modal"

![Simulator Screen Shot - iPhone X - 2019-04-09 at 15 24 21](https://user-images.githubusercontent.com/46673323/55825058-91163480-5adb-11e9-92b5-e7605d9553cf.png)

**Comment by yangbo5207** [comment]
+1，RN 0.59 会报这个错

**Comment by P21Marcelo** [comment]
@listenzz awesome work; ty.
