### ISSUE TITLE
低版本安卓似乎有点问题

### ISSUE THREAD

**Issue by shen-lan** [listenzz/react-native-modal-translucent#22]
1. 环境 安卓4.4， 锤子T1机型
2. modal内元素flex:1
3. 问题：
   a.顶部状态栏为黑色，应该是没有生效
   b.弹窗口有一定几率顶部顶出底部一部分
modal > View（flex:1,realtive） > BottomView(底部绝对定位)
![TIM图片20190424150745](https://user-images.githubusercontent.com/21122615/56639419-39fb8c80-66a3-11e9-966b-a733d4950e09.png)

**Comment by listenzz** [comment]
已验证，正在修复

**Comment by bashen1** [comment]
> 已验证，正在修复

高效率，感谢🙏
