### ISSUE TITLE
Bug on react-native version 0.59.8

### ISSUE THREAD

**Issue by Eddie-CooRo** [listenzz/react-native-modal-translucent#26]
Hi.
There is an issue with using this package with the version 0.59.8 react-native that causes the app to crash.
As of this [commit](https://github.com/facebook/react-native/commit/007e00fa70d0e1d69f7148e901790d2092e15b8c#diff-931cea019b5e9faceffef4e46f1fff08) react native no longer imports `requireNativeComponent` in the `Modal.js` file, So by copying this [line](https://github.com/listenzz/react-native-modal-translucent/blob/master/scripts/translucent-modal.js#L46) into the `Modal.js` file,  the app throws an error with the following message:
> can't find variable: requireNativeComponent

**Comment by bashen1** [comment]
@Eddie-CooRo 
open the 「 ⁨node_modules⁩ ▸ ⁨react-native⁩ ▸ ⁨Libraries⁩ ▸ ⁨Modal⁩ ▸ ⁨RCTModalHostViewNativeComponent.js」file

then add this line with top of the file
`const Platform = require('Platform');`

then replace the bottom line with this
`module.exports = (((Platform.OS === 'ios'?requireNativeComponent(
  'RCTModalHostView',
):requireNativeComponent('TranslucentModalHostView')): any): RCTModalHostViewNativeType);`

**Comment by 1612844** [comment]
You should update react-native 0.59.9 to and remove lib "react-native-modal-translucent"

**Comment by rajivshah3** [comment]
We fixed this by adding the following line [here](https://github.com/facebook/react-native/blob/c20070f10458d48d6ac1eaac49e681e932bfb9fd/Libraries/Modal/Modal.js#L22):

```js
const requireNativeComponent = require('requireNativeComponent');
```

After `npm run fix-modal` is complete, the file will look like this for RN 0.59.10:

```js
const AppContainer = require('AppContainer');
const I18nManager = require('I18nManager');
const NativeEventEmitter = require('NativeEventEmitter');
const NativeModules = require('NativeModules');
const Platform = require('Platform');
const React = require('React');
const PropTypes = require('prop-types');
const StyleSheet = require('StyleSheet');
const View = require('View');
const requireNativeComponent = require('requireNativeComponent');

const RCTModalHostView = Platform.OS === 'ios' ? requireNativeComponent('RCTModalHostView') : requireNativeComponent('TranslucentModalHostView');
```

**Comment by Eddie-CooRo** [comment]
@rajivshah3 I fixed this by using another library which doesn't mutate the react-native's source code

**Comment by listenzz** [comment]
Now, we don't need the scripts.
