### ISSUE TITLE
不支持 androidX

### ISSUE THREAD

**Issue by yangbo5207** [listenzz/react-native-modal-translucent#32]
构建时报错如下：
![image](https://user-images.githubusercontent.com/13758605/66458917-8185a180-eaa6-11e9-904a-45907e2b731a.png)

需要将上面这句删掉，使用下面箭头这个包

![image](https://user-images.githubusercontent.com/13758605/66458981-a548e780-eaa6-11e9-8339-dc59030f74a0.png)

希望大佬能更新一下，现在每次都手动改，比较麻烦

**Comment by listenzz** [comment]
4.0.0 已经支持
