### ISSUE TITLE
安装其他插件后失效

### ISSUE THREAD

**Issue by YanmaY** [listenzz/react-native-modal-translucent#6]
每次安装其他插件后，该插件就会失效，状态栏就又遮盖不住了，必须重新再安装一次插件才行。
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 1.36 GB / 7.89 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD     
      react-native-cli: 2.0.1
      react-native: 0.57.1
另外，每次安装的时候总会有一下警告：
![tim 20180928094157](https://user-images.githubusercontent.com/7043862/46183272-c3600180-c302-11e8-9876-c3e2300601a9.png)

**Comment by lhh-sofy** [comment]
遇到同样的问题了,求答案..

**Comment by listenzz** [comment]
在和 package.json 同级的目录下新建一个文件夹 scripts, 在该文件夹内创建一个叫 fix-modal.js 的文件，文件内容如下：

```javascript
const fs = require("fs-extra");
const path = require("path");

const modalPath = path.resolve(
  __dirname,
  "../node_modules/react-native/Libraries/Modal/Modal.js"
);

fs.readFile(modalPath, "utf8", function(err, data) {
  if (data.search("TranslucentModalHostView") === -1) {
    let str = data.replace(
      /^ *const +RCTModalHostView.*$/gm,
      `const RCTModalHostView = Platform.OS === 'ios' ? requireNativeComponent('RCTModalHostView') : requireNativeComponent('TranslucentModalHostView');`
    );
    fs.outputFile(modalPath, str);
  }
});
```
修改 package.json 文件, 添加 postinstall

```javascript
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "fixmodal": "node scripts/fix-modal.js",
    "postinstall": "npm run fixmodal"
  },
```

**Comment by lhh-sofy** [comment]
是每次新增组件时候都需要 执行一下 npm run fixmodal 吧，是要替换源代码是吧；
怎么能是yarn add时候 只添加相应的组件，不更新其余组件呢。。。

**Comment by listenzz** [comment]
配置了 postinstall, 每次你 npm install 或者 yarn install ,就会自动执行 npm run fixmodal

**Comment by chengsam** [comment]
@listenzz This is working, I think your should better mention this in readme.

**Comment by listenzz** [comment]
@chengsam Thank's for your remind.
