### ISSUE TITLE
react-native-image-zoom-viewer配合有问题

### ISSUE THREAD

**Issue by Evangelione** [listenzz/react-native-modal-translucent#7]
这个库解决了状态条留白的问题，但是配合react-native-image-zoom-viewer使用时，会把长按时的取消保存按钮盖到屏幕外面。。

"dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-image-zoom-viewer": "^2.2.23",
    "react-native-modal": "^6.5.0",
    "react-native-modal-translucent": "^1.1.5"

  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },

**Comment by Evangelione** [comment]
constructor(props) {
    super(props)
    this.state = {
      show: false,
    }
  }

  toggleModal = () => {
    this.setState({
      show: !this.state.show,
    })
  }

<View>
        <TouchableOpacity onPress={this.toggleModal } style={{marginTop: 100}}>
          <Text>showModal</Text>
        </TouchableOpacity>
        <Modal
          onBackButtonPress={this.toggleModal }
          onBackdropPress={this.toggleModal }
          isVisible={this.state.show}>
          <ImageViewer imageUrls={images}/>
        </Modal>
</View>

**Comment by Evangelione** [comment]
<View>
        <TouchableOpacity onPress={this.toggleModal } style={{marginTop: 100}}>
          <Text>showModal</Text>
        </TouchableOpacity>
        <Modal
          onBackButtonPress={this.toggleModal }
          onBackdropPress={this.toggleModal }
          isVisible={this.state.show}>
          <ImageViewer imageUrls={images}/>
        </Modal>
</View>

**Comment by Evangelione** [comment]
<TouchableOpacity onPress={this.toggleModal} style={{marginTop: 100}}>
          <Text>showModal</Text>
        </TouchableOpacity>
        <Modal
          onBackButtonPress={this.toggleModal}
          onBackdropPress={this.toggleModal}
          isVisible={this.state.show}>
          <ImageViewer imageUrls={images}/>
        </Modal>

**Comment by listenzz** [comment]
有没有图可以看下？

**Comment by Evangelione** [comment]
![_20181031163343](https://user-images.githubusercontent.com/24892968/47775585-0579ca00-dd2b-11e8-9c6d-349e2f8d3517.jpg)

本来底下是有个cancel按钮的，被盖到屏幕外面去了
