### ISSUE TITLE
虚拟按键遮挡布局问题

### ISSUE THREAD

**Issue by houweiAndroid** [listenzz/react-native-modal-translucent#8]
您好，我在安装了以后设置中间布局底部对其的时候，有时候会出现虚拟按键遮挡布局问题，请问下这个如何解决？
![image](https://user-images.githubusercontent.com/23226742/48828221-207baf00-edaa-11e8-8721-2a739e7e2233.png)

**Comment by listenzz** [comment]
请问如何重现呢？

**Comment by listenzz** [comment]
#7

**Comment by houweiAndroid** [comment]
多谢多谢🙏，解决了我的问题。
