### ISSUE TITLE
全面屏手机遮罩背景没有覆盖虚拟按键问题

### ISSUE THREAD

**Issue by houweiAndroid** [listenzz/react-native-modal-translucent#9]
您好，我今天用全面屏手机测试，发现全面屏手机遮罩背景没有覆盖虚拟按键，请问这个问题可以修复么？
![481542849874_ pic_hd](https://user-images.githubusercontent.com/23226742/48876441-0f2db380-ee39-11e8-812e-e7fc278c05b3.jpg)

**Comment by houweiAndroid** [comment]
您好，我用这个设置了宽高，它可以工作了。
        const deviceWidth = Dimensions.get("window").width;
        const deviceHeight = Platform.OS === "ios"
            ? Dimensions.get("window").height
            : require("react-native-extra-dimensions-android").get("REAL_WINDOW_HEIGHT");

**Comment by bashen1** [comment]
但是如果你的modal是从底部弹出，或者那块底部区域正好有按钮，这个按钮就时不时的无法被点到，设置了高度只能是遮罩层显示正确，根本原因还是未解决

**Comment by listenzz** [comment]
@bashen1 
现在有这个问题？

**Comment by bashen1** [comment]
> @bashen1
> 现在有这个问题？

我的错，是react-native-modal中包含了react-native-animatable，这个库的原因
